version: '3.7'

services:
  fastapi:
    image: xantes88/sentiment-analysis-api:latest  # Immagine FastAPI (da Docker Hub o locale)
    ports:
      - '8000:8000'  # Porta FastAPI esposta sulla 8000

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Monta il file di configurazione di Prometheus
    ports:
      - '9090:9090'  # Porta di Prometheus

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Imposta la password di amministratore
    ports:
      - '3000:3000'  # Porta di Grafana
