version: '3.7'

services:
  fastapi:
    image: xantes88/sentiment-analysis-api:latest  # Image for FastAPI (from Docker Hub or local)
    ports:
      - '8000:80'  # Expose FastAPI on port 8000

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount Prometheus config file
    ports:
      - '9090:9090'  # Expose Prometheus on port 9090

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set Grafana admin password
    ports:
      - '3000:3000'  # Expose Grafana on port 3000
