global:
  scrape_interval: 15s  # Frequenza con cui Prometheus raccoglie i dati

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:8000']  # Monitoraggio di FastAPI sulla porta 8000
