name: CI/CD Pipeline for Sentiment Analysis API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          pip install -r sentiment_analysis/requirements.txt

      # Step 4: Run Tests
      - name: Run Tests
        run: |
          pytest

      # Step 5: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t xantes88/sentiment-analysis-api:latest .

      # Step 6: Docker Login
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Push Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push xantes88/sentiment-analysis-api:latest
