name: CI/CD Pipeline for Sentiment Analysis API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          pip install -r sentiment_analysis/requirements.txt

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t xantes88/sentiment-analysis-api:latest .

      # Step 5: Docker Login
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Push Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push xantes88/sentiment-analysis-api:latest

      # Step 7: Download Prometheus Configuration File
      - name: Download prometheus.yml
        run: |
          curl -o prometheus.yml https://github.com/xantes88/sentiment-analysis-api/raw/main/prometheus.yml

      # Step 8: Create docker-compose.yml
      - name: Create docker-compose.yml
        run: |
          echo "version: '3.7'" > docker-compose.yml
          echo "services:" >> docker-compose.yml
          echo "  fastapi:" >> docker-compose.yml
          echo "    image: xantes88/sentiment-analysis-api:latest" >> docker-compose.yml
          echo "    ports:" >> docker-compose.yml
          echo "      - '8000:80'" >> docker-compose.yml
          echo "  prometheus:" >> docker-compose.yml
          echo "    image: prom/prometheus:latest" >> docker-compose.yml
          echo "    volumes:" >> docker-compose.yml
          echo "      - ./prometheus.yml:/etc/prometheus/prometheus.yml" >> docker-compose.yml
          echo "    ports:" >> docker-compose.yml
          echo "      - '9090:9090'" >> docker-compose.yml
          echo "  grafana:" >> docker-compose.yml
          echo "    image: grafana/grafana:latest" >> docker-compose.yml
          echo "    environment:" >> docker-compose.yml
          echo "      - GF_SECURITY_ADMIN_PASSWORD=admin" >> docker-compose.yml
          echo "    ports:" >> docker-compose.yml
          echo "      - '3000:3000'" >> docker-compose.yml

      # Step 9: Run Prometheus, Grafana, and FastAPI Containers
      - name: Start Prometheus, Grafana, and FastAPI Containers
        run: |
          docker-compose -f docker-compose.yml up -d

      # Step 10: Wait for Prometheus and Grafana to start
      - name: Wait for Prometheus and Grafana to start
        run: |
          sleep 30

      # Step 11: Test FastAPI app
      - name: Test FastAPI app
        run: |
          curl http://localhost:8000

      # Step 12: Monitor metrics in Grafana (Optional)
      - name: Monitor metrics in Grafana
        run: |
          echo "Grafana and Prometheus are up and running, check them at http://localhost:3000"
