name: CI/CD Pipeline for Sentiment Analysis API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          pip install -r sentiment_analysis/requirements.txt

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t xantes88/sentiment-analysis-api:latest .

      # Step 5: Docker Login
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Push Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push xantes88/sentiment-analysis-api:latest

      # Step 7: Download Prometheus Configuration File
      - name: Download prometheus.yml
        run: |
          curl -o prometheus.yml https://github.com/xantes88/sentiment-analysis-api/raw/main/prometheus.yml

      # Step 8: Run Prometheus, Grafana, and FastAPI Containers using docker-compose.yml
      - name: Start Prometheus, Grafana, and FastAPI Containers
        run: |
          docker-compose -f docker-compose.yml up -d

      # Step 9: Wait for Prometheus and Grafana to start
      - name: Wait for Prometheus and Grafana to start
        run: |
          sleep 30

      # Step 10: Test FastAPI app
      - name: Test FastAPI app
        run: |
          curl http://localhost:8000

      # Step 11: Monitor metrics in Grafana (Optional)
      - name: Monitor metrics in Grafana
        run: |
          echo "Grafana and Prometheus are up and running, check them at http://localhost:3000"
